--COLOR->EDITOR_BACKGROUND can be changed during runtime, but will have no effect.

local RESOURCES;

RESOURCES = {
	FONTS = {
		SYSTEM		= love.graphics.newFont(12);
		--CONSOLAS	= pcall(function() love.graphics.newFont("Consolas.ttf", 12) end) or RESOURCES.FONTS.SYSTEM;
		CODE		= love.graphics.newFont(14);
	};
	COLORS = {
		EDITOR_BACKGROUND							= {0, 0, 0, 1};
		
		FILEMENU_BACKGROUND							= {0.5, 0.5, 0.5, 1};
		FILEMENU_FOREGROUND							= {0, 0, 0, 1};
		FILEMENU_MENU_BACKGROUND					= {0.8, 0.8, 0.8, 1};
		
		ESCAPEMENU_BACKGROUND						= {0.2, 0.2, 0.2, 1};
		ESCAPEMENU_LIST_BACKGROUND					= {1, 1, 1, 1};
		ESCAPEMENU_LIST_FOREGROUND					= {0, 0, 0, 1};
		ESCAPEMENU_LIST_SELECTION_FOREGROUND		= {0, 0, 1, 1};
		ESCAPEMENU_LIST_SCROLLBAR_BACKGROUND		= {0.4, 0.4 ,0.4 ,1};
		ESCAPEMENU_LIST_SCROLLBAR_FOREGROUND		= {0.2, 0.6 ,0.2 ,1};
		
		ESCAPEMENU_BUTTON_BACKGROUND				= {0.4, 0.4, 0.4, 1};
		ESCAPEMENU_BUTTON_FOREGROUND				= {1, 1, 1, 1};
		
		TEXTAREA_BACKGROUND							= {0.9, 0.9, 0.9, 1};
		TEXTAREA_FOREGROUND							= {0, 0, 0, 1};
		TEXTAREA_CURSOR								= {1, 0, 0, 1};
		TEXTAREA_PANEL_FILEINFORMATION_BACKGROUND	= {0.2, 0.2, 0.6, 1};
		TEXTAREA_PANEL_FILEINFORMATION_FOREGROUND	= {0.2, 1, 0.2, 1};
		--TEXTAREA_LIST_LINENUMBER_BACKGROUND		= {0.7, 0.7, 0.7, 1};
		--TEXTAREA_LIST_LINENUMBER_FOREGROUND		= {0, 0, 0, 1};
		--TEXTAREA_VERTICAL_SCROLLBAR_BACKGROUND	= {0.1, 0.1 ,0.4 ,1};
		--TEXTAREA_VERTICAL_SCROLLBAR_FOREGROUND	= {0.2, 0.6 ,0.2 ,1};
	};
};

return RESOURCES;